[world]
name = "Provable Games"
description = "PG Sepolia World"
seed = "pg_sepolia"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x01ae9655937bde6abec7a89152ec645bc9a4993ddbb7d58075852f3dc8c39099"

[namespace]
default = "bodukan"

[writers]
# Tournament
"bodukan-Tournament" = ["bodukan-tournament_mock"]
"bodukan-Registration" = ["bodukan-tournament_mock"]
"bodukan-Leaderboard" = ["bodukan-tournament_mock"]
"bodukan-PlatformMetrics" = ["bodukan-tournament_mock"]
"bodukan-TournamentTokenMetrics" = ["bodukan-tournament_mock"]
"bodukan-PrizeMetrics" = ["bodukan-tournament_mock"]
"bodukan-EntryCount" = ["bodukan-tournament_mock"]
"bodukan-Prize" = ["bodukan-tournament_mock"]
"bodukan-Token" = ["bodukan-tournament_mock"]
"bodukan-TournamentConfig" = ["bodukan-tournament_mock"]
"bodukan-PrizeClaim" = ["bodukan-tournament_mock"]
# Game
"bodukan-GameMetadata" = ["bodukan-game_mock"]
"bodukan-GameCounter" = ["bodukan-game_mock"]
"bodukan-SettingsDetails" = ["bodukan-game_mock"]
"bodukan-TokenMetadata" = ["bodukan-game_mock"]
"bodukan-Score" = ["bodukan-game_mock"]

[migration]
order_inits = []
skip_contracts = ["bodukan-Bodukan"]