[world]
name = "Budokan"
description = "Budokan Slot World"
seed = "budokan"

[namespace]
default = "budokan_v_1_0_5"

[env]
chain_id = "WP_BUDOKAN"
rpc_url = "https://api.cartridge.gg/x/budokan/katana"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x04254b770ec69289dae26a6b488cc75689b3765171423cae8d648323ae4de44a"

[writers]
# Tournament
"budokan_v_1_0_5-Tournament" = ["budokan_v_1_0_5-tournament_mock"]
"budokan_v_1_0_5-Registration" = ["budokan_v_1_0_5-tournament_mock"]
"budokan_v_1_0_5-Leaderboard" = ["budokan_v_1_0_5-tournament_mock"]
"budokan_v_1_0_5-PlatformMetrics" = ["budokan_v_1_0_5-tournament_mock"]
"budokan_v_1_0_5-TournamentTokenMetrics" = ["budokan_v_1_0_5-tournament_mock"]
"budokan_v_1_0_5-PrizeMetrics" = ["budokan_v_1_0_5-tournament_mock"]
"budokan_v_1_0_5-EntryCount" = ["budokan_v_1_0_5-tournament_mock"]
"budokan_v_1_0_5-Prize" = ["budokan_v_1_0_5-tournament_mock"]
"budokan_v_1_0_5-Token" = ["budokan_v_1_0_5-tournament_mock"]
"budokan_v_1_0_5-TournamentConfig" = ["budokan_v_1_0_5-tournament_mock"]
"budokan_v_1_0_5-PrizeClaim" = ["budokan_v_1_0_5-tournament_mock"]
"budokan_v_1_0_5-QualificationEntries" = ["budokan_v_1_0_5-tournament_mock"]
# Game
"budokan_v_1_0_5-GameMetadata" = ["budokan_v_1_0_5-game_mock"]
"budokan_v_1_0_5-GameCounter" = ["budokan_v_1_0_5-game_mock"]
"budokan_v_1_0_5-SettingsDetails" = ["budokan_v_1_0_5-game_mock"]
"budokan_v_1_0_5-SettingsCounter" = ["budokan_v_1_0_5-game_mock"]
"budokan_v_1_0_5-Settings" = ["budokan_v_1_0_5-game_mock"]
"budokan_v_1_0_5-TokenMetadata" = ["budokan_v_1_0_5-game_mock"]
"budokan_v_1_0_5-Score" = ["budokan_v_1_0_5-game_mock"]

[migration]
order_inits = []
skip_contracts = ["budokan_v_1_0_5-Budokan"]
