[world]
name = "Realms World"
website = "https://realms.world/"
description = "DNC"
seed = "DNC"

[env]
chain_id = "SN_MAINNET"
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x06a9e4c6f0799160ea8ddc43ff982a5f83d7f633e9732ce42701de1288ff705f"
world_block = 948010

[namespace]
default = "bodukan"

[writers]
"bodukan" = ["bodukan-Bodukan"]

[init_call_args]
"bodukan-Bodukan" = [
    "1", # safe_mode
    "0" # test_mode
]

[migration]
order_inits = []
skip_contracts = [
    "bodukan-tournament_mock", 
    "bodukan-game_mock", 
    "bodukan-erc20_mock", 
    "bodukan-erc721_mock", 
]
