[world]
name = "Budokan"
description = "Budokan Slot World"
seed = "budokan"

[namespace]
default = "budokan_1_0_8"

[env]
chain_id = "WP_BUDOKAN"
rpc_url = "https://api.cartridge.gg/x/budokan-katana/katana"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x04254b770ec69289dae26a6b488cc75689b3765171423cae8d648323ae4de44a"

[writers]
# Tournament
"budokan_1_0_8" = ["budokan_1_0_8-tournament_mock"]

[init_call_args]
"budokan_1_0_8-Budokan" = [
    "0", # safe_mode
    "0", # test_mode
    "0x0", # denshokan address
    "1", # array length
    "0x0", # token address
    "0", # token type
]


[migration]
order_inits = []
skip_contracts = ["budokan_1_0_8-Budokan"]
