[world]
name = "Realms World"
website = "https://realms.world/"
description = "DNC"
seed = "DNC"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x3fcff8ebdff3a82dfb72246cecbffabbd22ecfe47d34ad7cb809f982ffda206"

[namespace]
default = "budokan_1_0_8"

[writers]
"budokan_1_0_8" = ["budokan_1_0_8-Budokan"]

[init_call_args]
"budokan_1_0_8-Budokan" = [
    "0", # safe_mode
    "0", # test_mode
    "0x0466f3c79b045ade0bd19a4dc2835c1cf9af7bea0166a6c1df9e9ad73dbf4cb6", # denshokan address
    "2", # array length
    "0x049D36570D4e46f48e99674bd3fcc84644DdD6b96F7C741B1562B82f9e004dC7", # token address
    "0", # token type
    "0x04718f5a0Fc34cC1AF16A1cdee98fFB20C31f5cD61D6Ab07201858f4287c938D", # token address
    "0", # token type
]