[world]
name = "Budokan"
description = "Budokan Slot World"
seed = "budokan"

[namespace]
default = "budokan_1_0_8"

[env]
rpc_url = "https://api.cartridge.gg/x/pg-slot-2/katana"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x3fcff8ebdff3a82dfb72246cecbffabbd22ecfe47d34ad7cb809f982ffda206"

[writers]
# Tournament
"budokan_1_0_8" = ["budokan_1_0_8-Budokan"]

[init_call_args]
"budokan_1_0_8-Budokan" = [
    "0", # safe_mode
    "0", # test_mode
    "0x01577ca1fb06c82066c78ff9088fe3d5ef639a7658bfe7edffec76df03afeedb", # denshokan address
    "0", # array length
    # "0x0", # token address
    # "0", # token type
]
