[world]
name = "Provable Games"
description = "PG Slot World"
seed = "pg"

[namespace]
default = "budokan"

[env]
chain_id = "WP_PG"
rpc_url = "https://api.cartridge.gg/x/pg/katana"
account_address = "0x5b6b8189bb580f0df1e6d6bec509ff0d6c9be7365d10627e0cf222ec1b47a71"
private_key = "0x33003003001800009900180300d206308b0070db00121318d17b5e6262150b"
world_address = "0x04254b770ec69289dae26a6b488cc75689b3765171423cae8d648323ae4de44a"

[writers]
# Tournament
"budokan-Tournament" = ["budokan-tournament_mock"]
"budokan-Registration" = ["budokan-tournament_mock"]
"budokan-Leaderboard" = ["budokan-tournament_mock"]
"budokan-PlatformMetrics" = ["budokan-tournament_mock"]
"budokan-TournamentTokenMetrics" = ["budokan-tournament_mock"]
"budokan-PrizeMetrics" = ["budokan-tournament_mock"]
"budokan-EntryCount" = ["budokan-tournament_mock"]
"budokan-Prize" = ["budokan-tournament_mock"]
"budokan-Token" = ["budokan-tournament_mock"]
"budokan-TournamentConfig" = ["budokan-tournament_mock"]
"budokan-PrizeClaim" = ["budokan-tournament_mock"]
# Game
"budokan-GameMetadata" = ["budokan-game_mock"]
"budokan-GameCounter" = ["budokan-game_mock"]
"budokan-SettingsDetails" = ["budokan-game_mock"]
"budokan-TokenMetadata" = ["budokan-game_mock"]
"budokan-Score" = ["budokan-game_mock"]

[migration]
order_inits = []
skip_contracts = ["budokan-Budokan"]
