[world]
name = "Realms World"
website = "https://realms.world/"
description = "DNC"
seed = "DNC"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x29f11cefb67df8a3962ba60816800ccf196f9497ae781bb4bc8589f8e245753"

[namespace]
default = "budokan_1_0_8"

[writers]
"budokan_1_0_8" = ["budokan_1_0_8-Budokan"]

[init_call_args]
"budokan_1_0_8-Budokan" = [
    "0", # safe_mode
    "0", # test_mode
    "0x06a1102ed881e0d6d689295db5819dd1d15f0d55cbe10e1b87587c2ea1ec8da4", # denshokan address
    "0", # array length - ON SEPOLIA ALL TOKENS ARE REGISTERED
]