[world]
name = "Realms World"
website = "https://realms.world/"
description = "DNC"
seed = "DNC"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_8"
world_address = "0x785401cf74071ec444e37dbbd87281aba48afc86570b1a1537193d1ce39086f"

[namespace]
default = "budokan_1_0_8"

[writers]
"budokan_1_0_8" = ["budokan_1_0_8-Budokan"]

[init_call_args]
"budokan_1_0_8-Budokan" = [
    "0x02334dc9c950c74c3228e2a343d495ae36f0b4edf06767a679569e9f9de08776", # denshokan address
    "0", # array length - ON SEPOLIA ALL TOKENS ARE REGISTERED
]