[world]
name = "Tournaments"
description = "Test Tournaments deployment on slot"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "tournaments"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "tournaments"

[env]
chain_id = "WP_TOURNAMENTS"
rpc_url = "https://api.cartridge.gg/x/tournaments/katana"
account_address = "0x5b6b8189bb580f0df1e6d6bec509ff0d6c9be7365d10627e0cf222ec1b47a71"
private_key = "0x33003003001800009900180300d206308b0070db00121318d17b5e6262150b"
# world_address = "0x02b127646258e21186e6c7e6234f42583d0d19bf88a57776a404c2cefeb421f2"  # Uncomment and update this line with your world address.

[writers]
# Tournament
"tournaments-Tournament" = ["tournaments-tournament_mock"]
"tournaments-Registration" = ["tournaments-tournament_mock"]
"tournaments-Leaderboard" = ["tournaments-tournament_mock"]
"tournaments-PlatformMetrics" = ["tournaments-tournament_mock"]
"tournaments-TournamentTokenMetrics" = ["tournaments-tournament_mock"]
"tournaments-PrizeMetrics" = ["tournaments-tournament_mock"]
"tournaments-EntryCount" = ["tournaments-tournament_mock"]
"tournaments-Prize" = ["tournaments-tournament_mock"]
"tournaments-Token" = ["tournaments-tournament_mock"]
"tournaments-TournamentConfig" = ["tournaments-tournament_mock"]
"tournaments-PrizeClaim" = ["tournaments-tournament_mock"]
# Game
"tournaments-GameMetadata" = ["tournaments-game_mock"]
"tournaments-GameCount" = ["tournaments-game_mock"]
"tournaments-SettingsDetails" = ["tournaments-game_mock"]
"tournaments-TokenMetadata" = ["tournaments-game_mock"]
"tournaments-Score" = ["tournaments-game_mock"]

[migration]
order_inits = []
skip_contracts = ["tournaments-Tournament"]
