[package]
cairo-version = "=2.8.4"
name = "tournaments"
version = "0.0.1"
edition = "2024_07"

[lib]

[[target.starknet-contract]]
sierra = true
# It's important to keep this, since it's used by Sozo to check the world version.
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
openzeppelin_introspection = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.18.0"}
openzeppelin_token = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.18.0"}
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.9" }
starknet = "2.8.4"

[dev-dependencies]
# This package is required to run tests and add dojo utilities to your project in test only.
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.9" }

[features]
default = []

#--------------------------
# Dojo profiles declaration
#
[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]