[package]
cairo-version = "=2.10.1"
name = "tournaments"
version = "0.0.1"
edition = "2024_07"

[lib]

[[target.starknet-contract]]
sierra = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "achievement::events::index::e_TrophyCreation",
    "achievement::events::index::e_TrophyProgression",
]

[dependencies]
openzeppelin_introspection = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v1.0.0"}
openzeppelin_token = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v1.0.0"}
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.5.0" }
achievement = { git = "https://github.com/cartridge-gg/arcade" }
starknet = "2.10.1"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.5.0" }
cairo_test = "2.10.1"

[features]
default = []

[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]