[package]
cairo-version = "=2.10.1"
name = "tournaments"
version = "0.0.1"
edition = "2024_07"

[lib]

[[target.starknet-contract]]
sierra = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "game_components_minigame::tests::models::minigame::m_ScoreObjective",
    "game_components_minigame::tests::models::minigame::m_ScoreObjectiveCount",
    "game_components_minigame::tests::models::minigame::m_Settings",
    "game_components_minigame::tests::models::minigame::m_SettingsDetails",
    "game_components_minigame::tests::models::minigame::m_SettingsCounter",
    "game_components_minigame::tests::models::minigame::m_Score",
    "game_components_minigame::tests::mocks::minigame_mock::minigame_mock",
]

[dependencies]
openzeppelin_introspection = "1.0.0"
openzeppelin_token = "1.0.0"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.1" }
game_components_denshokan = { git = "https://github.com/Provable-Games/game-components", branch = "main" }
game_components_metagame = { git = "https://github.com/Provable-Games/game-components", branch = "main" }
game_components_minigame = { git = "https://github.com/Provable-Games/game-components", branch = "main" }
game_components_utils = { git = "https://github.com/Provable-Games/game-components", branch = "main" }
denshokan = { git = "https://github.com/Provable-Games/denshokan", branch = "main" }
starknet = "2.10.1"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.5.1" }
cairo_test = "2.10.1"

[features]
default = []

[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]