[package]
cairo-version = "=2.10.1"
name = "budokan"
version = "0.0.1"
edition = "2024_07"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "game_components_test_starknet::minigame::mocks::minigame_starknet_mock::minigame_starknet_mock",
    "game_components_test_starknet::metagame::mocks::metagame_starknet_mock::metagame_starknet_mock",
    "game_components_token::examples::full_token_contract::FullTokenContract",
    "game_components_token::examples::minigame_registry_contract::MinigameRegistryContract",
]

[dependencies]
openzeppelin_introspection = "1.0.0"
openzeppelin_token = "1.0.0"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.2" }
game_components_metagame = { git = "https://github.com/Provable-Games/game-components", tag = "0.0.6" }
game_components_minigame = { git = "https://github.com/Provable-Games/game-components", tag = "0.0.6" }
game_components_utils = { git = "https://github.com/Provable-Games/game-components", tag = "0.0.6" }
game_components_test_starknet = { git = "https://github.com/Provable-Games/game-components", tag = "0.0.6" }
game_components_token = { git = "https://github.com/Provable-Games/game-components", tag = "0.0.6" }
starknet = "2.10.1"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.6.2" }
cairo_test = "2.10.1"

[features]
default = []

[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]