rpc = "https://api.cartridge.gg/x/starknet/mainnet"

# Eternum S1 World
world_address = "0x5c6d0020a9927edca9ddc984b97305439c0b32a1ec8d3f0eaf6291074cc9799"


[indexing]
events_chunk_size = 1024  # Size of events page to fetch
blocks_chunk_size = 10240 # Blocks to process before DB commit

pending = true # Enable indexing pending blocks

polling_interval = 500 # Polling interval in milliseconds

max_concurrent_tasks = 100 # Maximum concurrent indexing tasks

transactions = true

contracts = [
	"erc721:0x60e8836acbebb535dfcd237ff01f20be503aae407b67bb6e3b5869afae97156",
	"erc721:0x7ad410c472c1d61ce318dd617a479c977c85275afbf7991a1e1461ffe626a3d",
    "erc721:0x01e1c477f2ef896fd638b50caa31e3aa8f504d5c6cb3c09c99cd0b72523f07f7", # dark shuffle v1.2.1
    "erc721:0x1e0b80823ba036c8366c2434dad9d5bb35662a7b1d0afbdc69c5f0a7fff3513" # zkube v1.0.0
]

namespaces = ["ds_v1_2_0", "budokan_v_1_0_7", "zkube_budo_v1_1_0"]

world_block = 1385471 # world deployment block - 10
#https://voyager.online/tx/0x3ffdcecd7357033b2b2ac7bbe0c290555190dd79edec6e19f529df498243b32

[erc]
max_metadata_tasks = 5

[sql]
all_model_indices = false

[server]
http_cors_origins = ["*"]

[events]
raw = false